/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Models.Session;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizky Alif - 2KS2
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setTitle("Main Menu - MAVIA'S");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        side_image1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mahasiswaButton = new javax.swing.JButton();
        uangkasButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kegiatanButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 490));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(615, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-transformed.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 40, 40));

        side_image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mavias2.jpeg"))); // NOI18N
        side_image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.add(side_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("MAIN MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        mahasiswaButton.setBackground(new java.awt.Color(102, 102, 102));
        mahasiswaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mahasiswa-transformed.png"))); // NOI18N
        mahasiswaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mahasiswaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 140, 100));

        uangkasButton.setBackground(new java.awt.Color(204, 204, 255));
        uangkasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rupiah-transformed.png"))); // NOI18N
        uangkasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangkasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uangkasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 140, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Schedule");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Members");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        kegiatanButton.setBackground(new java.awt.Color(255, 204, 102));
        kegiatanButton.setForeground(new java.awt.Color(160, 0, 0));
        kegiatanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/schedule-transformed.png"))); // NOI18N
        kegiatanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kegiatanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kegiatanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Uang Kas\n");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            // Dispose the current frame and show the login frame
            this.dispose();
            new Login().setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "Anda Berhasil Logout");
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void mahasiswaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaButtonActionPerformed
        // TODO add your handling code here:
        new MahasiswaFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_mahasiswaButtonActionPerformed

    private void uangkasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangkasButtonActionPerformed
        // TODO add your handling code here:
        new UangKas().setVisible(true);
        dispose();
    }//GEN-LAST:event_uangkasButtonActionPerformed

    private void kegiatanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kegiatanButtonActionPerformed
        // TODO add your handling code here:
        new Kegiatan().setVisible(true);
        dispose();
    }//GEN-LAST:event_kegiatanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        if (!Session.isAuthenticated()) {
            JOptionPane.showMessageDialog(null, "Harap Login Terlebih Dahulu.");
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new Login().setVisible(true);
                }
            });
        } else {
            // Jika sudah terautentikasi, lanjutkan ke main menu atau halaman lain
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new MainMenu().setVisible(true);
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kegiatanButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mahasiswaButton;
    private javax.swing.JLabel side_image1;
    private javax.swing.JButton uangkasButton;
    // End of variables declaration//GEN-END:variables
}
